### ISSUE TITLE
[ENH] Add ApplyMerges Function  

### ISSUE THREAD

**Issue by scovitz** [PennLINC/BOnD#18]
Way of harmonizing metadata. Change sidecars to match the param group you want to merge into.

**Comment by mattcieslak** [comment]
This will need a couple features:

 - [ ] a CLI entrypoint
 - [ ] a function that checks that the list of changes is possible (ie fieldmap keys are compatible)
 - [ ] add to the apply CSV function lines that call the CLI entrypoint with from and to json files
